version: 1.0.{build}
configuration: Release
platform: Any CPU
environment:
  matrix:
  - solution_name: ORM.sln
#  - solution_name: OrmLanguage\OrmLanguage.sln
build_script:
- msbuild %solution_name%
install:
- ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
before_build:
- appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v3.2.0-rc/nuget.exe
- appveyor DownloadFile https://raw.githubusercontent.com/appveyor/ci/master/scripts/nuget-restore.cmd
- nuget-restore
after_build:
- nuget pack SimpleOrm.nuspec -Prop Configuration=%CONFIGURATION% -Prop version=%APPVEYOR_BUILD_VERSION%
artifacts:
- path: ORM\bin\$(configuration)
  name: ORM
- path: SimpleOrm.*.nupkg
  name: Nuget
- path: ORM.VSPackage\bin\$(configuration)
  name: VSPackage
- path: Output\Company.OrmLanguage.DslPackage.2013.vsix
  name: OrmLanguage
deploy:
- provider: GitHub
  description: Simple ORM
  auth_token:
    secure: lQ8ijoj6dfshLfFWRKFUrphgt4LkIz1YduZU+S6xuF33ewz1WcySLNJURJysTF11
  artifact: ORM,Nuget,VSPackage, OrmLanguage
  on:
    branch: master
    appveyor_repo_tag: true
- provider: NuGet
  api_key:
    secure: pziM2WPIuSTwZLLV+APtqvUB5JqK0bpFIW/DfuYBmD7YjyKoO21px5aHY/qMTQef
  artifact: Nuget
  on:
    branch: master
    appveyor_repo_tag: true
after_deploy:
# - ps: Vsix-PublishToGallery ORM.VSPackage\bin\$env:CONFIGURATION\*.vsix
# - ps: Vsix-PublishToGallery Output\*.vsix